
## Gopkg.toml example (these lines may be deleted)

## "metadata" defines metadata about the project that could be used by other independent
## systems. The metadata defined here will be ignored by dep.
# [metadata]
# key1 = "value that convey data to other systems"
# system1-data = "value that is used by a system"
# system2-data = "value that is used by another system"

## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
# required = ["github.com/user/thing/cmd/thing"]

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
# ignored = ["github.com/user/project/badpkg"]

## Constraints are rules for how directly imported projects
## may be incorporated into the depgraph. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
# [[constraint]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"
#
## "metadata" defines metadata about the dependency or override that could be used
## by other independent systems. The metadata defined here will be ignored by dep.
# [metadata]
# key1 = "value that convey data to other systems"
# system1-data = "value that is used by a system"
# system2-data = "value that is used by another system"

## Overrides have the same structure as [[constraint]], but supersede all
## [[constraint]] declarations from all projects. Only [[override]] from
## the current project's are applied.
##
## Overrides are a sledgehammer. Use them only as a last resort.
# [[override]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Optional: specifying a version constraint override will cause all other
## constraints on this project to be ignored; only the overridden constraint
## need be satisfied.
## Again, only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: specifying an alternate source location as an override will
## enforce that the alternate location is used for that project, regardless of
## what source location any dependent projects specify.
# source = "https://github.com/myfork/package.git"



[[constraint]]
  name = "cloud.google.com/go"
  # we are mostly fine on 0.6.0 only real feature that is obviously missing
  # and not very important is the job.Statistics on bigquery
  version = "0.6.0"
  # branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/araddon/dateparse"

[[constraint]]
  branch = "master"
  name = "github.com/araddon/gou"

[[constraint]]
  branch = "identity_quote"
  name = "github.com/araddon/qlbridge"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.1.6"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/pkg"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "2.6.1"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.2.0"

[[constraint]]
  name = "github.com/emicklei/go-restful-swagger12"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/loads"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[[constraint]]
  branch = "master"
  name = "github.com/go-sql-driver/mysql"

[[constraint]]
  branch = "master"
  name = "github.com/gocql/gocql"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/hailocab/go-hostpool"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/juju/ratelimit"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"

[[constraint]]
  branch = "master"
  name = "github.com/lytics/cloudstorage"

[[constraint]]
  branch = "master"
  name = "github.com/lytics/confl"

[[constraint]]
  branch = "master"
  name = "github.com/lytics/dfa"

[[constraint]]
  branch = "master"
  name = "github.com/lytics/go-lytics"

[[constraint]]
  branch = "small_mods"
  name = "github.com/lytics/grid"

[[constraint]]
  branch = "master"
  name = "github.com/mattbaird/elastigo"

[[constraint]]
  branch = "master"
  name = "github.com/sony/sonyflake"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "master"
  name = "k8s.io/client-go"
